version: "3"

services:
  web:
    build:
      dockerfile: Dockerfile
    command: 'bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"'
    ports:
      - 8000:8000
      - 8080:8000
      - 777:8000
    volumes:
      - ./:/app
    restart: on-failure
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD=bdpassword
      - POSTGRES_USER=stas
      - POSTGRES_DB=diploma_db
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - /home/stas/PycharmProjects/DIplom/data:/var/lib/postgresql/data
    ports:
      - 5432:5432