# Generated by Django 5.0.4 on 2024-04-26 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Image',
            field=models.ImageField(null=True, upload_to='books/'),
        ),
    ]
