# Generated by Django 5.0.4 on 2024-04-26 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_book_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='Image',
            new_name='image',
        ),
    ]
