# Generated by Django 4.2.13 on 2024-05-08 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0007_recommendedbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendedbook',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_recommendations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recommendedbook',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommended_books', to='main.book'),
        ),
        migrations.AlterField(
            model_name='recommendedbook',
            name='recommended',
            field=models.ManyToManyField(null=True, related_name='recommendations_for', to='main.book'),
        ),
    ]
