# Generated by Django 4.2.13 on 2024-05-08 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_recommendedbook_user_alter_recommendedbook_book_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendedbook',
            name='book',
        ),
    ]
