# Generated by Django 4.2.13 on 2024-05-20 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_book_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='weight',
            field=models.DecimalField(decimal_places=5, max_digits=5, null=True),
        ),
    ]
